[package]
name = "hello-twitch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "3"
tokio = { version = "1.10.0", features = ["full"] }
